dataDir: data
patterns:
  prerequisites:
    - pd.read_csv(deba.data(r'.+\.csv'))
  references:
    - files_meta_frame(r'.+\.dvc')
  targets:
    - "`*`.to_csv(deba.data(r'.+\\.csv'))"
stages:
  - name: meta
  - name: ocr
    commonPrerequisites:
      - ocr_results
  - name: ner
  - name: clean
    ignoredTargets:
      - duplicates.csv
  - name: match
  - name: fuse_agency
    ignoredTargets:
      - duplicates.csv
    commonPrerequisites:
      - datavalid.yml
  - name: match_history
  - name: analysis
  - name: fuse
    ignoredTargets:
      - fuse/person.csv
targets:
  - fuse/allegation.csv
  - fuse/personnel.csv
  - fuse/use_of_force.csv
  - fuse/stop_and_search.csv
  - fuse/appeals.csv
  - fuse/event.csv
  - fuse/citizens.csv
  - fuse/agency_reference_list.csv
  - fuse/documents.csv
  - fuse/person.csv
  - analysis/coaccusals.csv
